server:
  port: 9090

spring:
  security:
    user:
      name: admin  # Admin username
      password: admin123  # Admin password (consider using a stronger password)
  boot:
    admin:
      security:
        enabled: true  # Enable security for the Admin UI
      client:
        url:
      instance:
        service-url: http://localhost:9090  # Service URL for other services
      ui:
        title: "Microservices Admin"  # Title of the Admin UI
        path: /admin  # Path to access the Admin UI
      log-level: INFO  # Set logging level for Spring Boot Admin


