spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication
          uri: lb://authentication
          predicates:
            - Path=/authentication/**
        - id: course
          uri: lb://course
          predicates:
            - Path=/courses/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/orders/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/payments/**


server:
  port: 8080
